#cloud-config
ssh_pwauth: true
chpasswd:
  expire: false

users:
  - name: ansible
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ${ansible_ssh_key}
  
  - name: teacher
    groups: sudo
    shell: /bin/bash
    lock_passwd: false
    plain_text_passwd: '12345678'
