[workers]
worker-node ansible_host=192.168.122.42

[db]
db-node ansible_host=192.168.122.38

[all:vars]
ansible_user=ansible
ansible_ssh_private_key_file=~/.ssh/ansible_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'